import type { Metadata } from 'next';
import './globals.css';
import AntdRegistry from '../components/antd-registry';

export const metadata: Metadata = {
  title: 'Admin System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
